### ISSUE TITLE
allow custom prompts

### ISSUE THREAD

**Issue by simonpcouch** [simonpcouch/pal#4]
I'm thinking that `pal(role)` will always be an enum _except_ when supplied a connection to a markdown file. That connection could be wrapped with some helper that adds a class so that `pal()` knows not to error out.

e.g.:

```r
# pre-defined option
pal("cli")

# would error out
pal("some_custom_prompt.md")

# works
pal(prompt("some_custom_prompt.md"))
```

**Comment by jcheng5** [comment]
Some other ideas:

1. An easy way to look for prompts in a user-scoped directory (like `~/.config/pal/prompts`). I figure I'll want my pals to be with me no matter what project I'm working on, or no matter what version of R.
2. An easy way to use prompts from GitHub repos or gists--if you do 👆 then maybe a helper function that, given a gist downloads it into the default directory.
3. A playground mode where you provide some code and a selection, and can quickly iterate on your pal prompt.

**Comment by simonpcouch** [comment]
Woops, didn't mean to close.🤦

**Comment by simonpcouch** [comment]
Following up on 2103c43 and bbdf23c, going to go ahead and close! Certainly more work to do, but feeling pretty solid about the general idea here.
