### ISSUE TITLE
Unable to get pals to run in RStudio

### ISSUE THREAD

**Issue by dkutner** [simonpcouch/pal#64]
I'm unable to get pals to run through the RStudio UI. The modal pops up when I hit Ctrl+Alt+P, but nothing happens when I select a pal. I've tried filtering for one by typing a prefix or the full name and hitting Enter, and the modal closes, but nothing happens.

I have no issues running pals by initializing them and calling their `$chat()` function.

I'm running R 4.2.3 and RStudio 2024.09.1 on Windows with `pal 0.0.2` and Ollama.

**Comment by dkutner** [comment]
Updating shiny (and some dependencies) fixed the issue.

**Comment by simonpcouch** [comment]
Ah, interesting. Thanks for the issue! I'll reopen to remind myself to set minimum package versions for some package dependencies.
